- name: Copy edgeboxctl.service
  ansible.builtin.copy:
    src: /tmp/bin/edgeboxctl/edgeboxctl.service
    dest: /lib/systemd/system/edgeboxctl.service

- name: Copy edgeboxctl
  ansible.builtin.copy:
    src: /tmp/bin/edgeboxctl/edgeboxctl-linux-amd64
    dest: /usr/local/sbin/edgeboxctl

- name: Copy ws
  ansible.builtin.copy:
    src: /tmp/bin/ws
    dest: /home/system/components/ws

- name: Copy api
  ansible.builtin.copy:
    src: /tmp/bin/api
    dest: /home/system/components/api

- name: Copy apps
  ansible.builtin.copy:
    src: /tmp/bin/apps
    dest: /home/system/components/apps

- name: Create data dir
  ansible.builtin.file:
    path: /home/system/components/appdata
    state: directory
    mode: '0777'

- name: Build reverse proxy and service containers configs
  ansible.builtin.shell: ./ws -b
  args:
    chdir: /home/system/components/ws

- name: Start reverse proxy and service containers
  ansible.builtin.shell: ./ws -s
  args:
    chdir: /home/system/components/ws

- name: Just force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable service edgeboxctl and ensure it is not masked
  ansible.builtin.systemd:
    name: edgeboxctl
    enabled: true
    masked: no  

- name: Make sure a edgeboxctl is running
  ansible.builtin.systemd:
    state: started
    name: edgeboxctl
